# Generated by Django 6.0.6 on 2026-06-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='Flight',
        ),
    ]
